
package aplikasikepegawaian;

import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author User
 */
public class TransaksiGajih extends javax.swing.JFrame {
    String[] Data = {"Nama", "Jabatan","ID","Gajih","Lembur","Uang Lembur","Total gaji"};
    String[] Field = {"nama", "jabatan","id","gajih","lembur","uanglembur","total"};
    String SQL = "SELECT * FROM transaksi";
    int[] Lebar ={120,120,50,70,70,100,100};
    
    public TransaksiGajih() {
        backend_UASPBO transaksi = new backend_UASPBO();
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        new backend_UASPBO().JudulJtable(jTable1, Data);
        new backend_UASPBO().tampilTabel(Data, SQL, jTable1);
        new backend_UASPBO().LebarJTable(jTable1, Lebar);
        DefaultComboBoxModel cmblembur = new DefaultComboBoxModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtgaji = new javax.swing.JTextField();
        txtuanglembur = new javax.swing.JTextField();
        cmbjabatan = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmblembur = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnhitung = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Program Transaksi Gajih Pegawai");

        jLabel2.setText("Nama");

        jLabel3.setText("Jabatan");

        jLabel4.setText("Gajih");

        txtgaji.setEditable(false);

        txtuanglembur.setEditable(false);

        cmbjabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jabatan", "Direktur", "Manager", "Admin", "Staf Administrasi", "Staf Manager" }));
        cmbjabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbjabatanActionPerformed(evt);
            }
        });

        jLabel5.setText("Lembur");

        cmblembur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih lama jam lembur", "1 jam", "2 jam", "3 jam", "4 jam", "5 jam" }));
        cmblembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmblemburActionPerformed(evt);
            }
        });

        jLabel6.setText("Uang Lembur");

        btnhitung.setBackground(new java.awt.Color(0, 153, 153));
        btnhitung.setText("Hitung");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        jLabel8.setText("Total Gajih");

        txttotal.setEditable(false);

        jLabel7.setText("ID Jabatan ");

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 153, 153));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton5.setText("Cetak");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton2.setText("Ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(0, 153, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel9.setText("Cari Data");

        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcari)
                            .addComponent(txtgaji)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cmbjabatan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cmblembur, 0, 285, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtuanglembur, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txttotal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtnama)
                            .addComponent(btnhitung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtgaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmblembur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtuanglembur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnhitung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbjabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbjabatanActionPerformed
      if(cmbjabatan.getSelectedItem().equals("Pilih Jabatan")) {
          txtgaji.setText("");
      } 
      else if(cmbjabatan.getSelectedItem().equals("Direktur")) {
          txtgaji.setText("5000000"); txtid.setText("D087");
      } 
      else if(cmbjabatan.getSelectedItem().equals("Manager")) {
          txtgaji.setText("3500000"); txtid.setText("D098");
      } 
      else if(cmbjabatan.getSelectedItem().equals("Admin")) {
          txtgaji.setText("2500000"); txtid.setText("D490");
      } 
      else if(cmbjabatan.getSelectedItem().equals(" Staf Administrasi")) {
          txtgaji.setText("2000000"); txtid.setText("D476");
      } 
      else if(cmbjabatan.getSelectedItem().equals("Staf Manager")) {
          txtgaji.setText("2000000"); txtid.setText("D022");
      } 
      
// TODO add your handling code here:
    }//GEN-LAST:event_cmbjabatanActionPerformed

    private void cmblemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmblemburActionPerformed
    String pil = cmblembur.getSelectedItem().toString();
    if(pil.equals("Pilih lama jam lembur")) {
      txtuanglembur.setText("");
      } 
      else if(pil.equals("1 jam")) {
          txtuanglembur.setText("50000");
      } 
      else if(pil.equals("2 jam")) {
          txtuanglembur.setText("100000");
      } 
      else if(pil.equals("3 jam")) {
          txtuanglembur.setText("150000");
      } 
      else if(pil.equals("4 jam")) {
          txtuanglembur.setText("200000");
      } 
      else if(pil.equals("5 jam")) {
          txtuanglembur.setText("250000");
      } 
// TODO add your handling code here:
    }//GEN-LAST:event_cmblemburActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
       int x = Integer.parseInt(txtgaji.getText());
       int y = Integer.parseInt(txtuanglembur.getText());
       int z = x+y;
       txttotal.setText(String.valueOf(z));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhitungActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        txtnama.setText("");
        cmbjabatan.setSelectedItem("Pilih Jabatan");
        txtid.setText("");
        txtgaji.setText("");
        cmblembur.setSelectedItem("Pilih lama jam lembur");
        txtuanglembur.setText("");
        txttotal.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        java.sql.Connection con = null;

        try{
            String jdbcDriver = "com.mysql.jdbc.Driver";
            Class.forName(jdbcDriver);
            String url ="jdbc:mysql://localhost:3306/uaspbo";
            String user ="root";
            String pass = "";

            con = DriverManager.getConnection(url, user, pass);
            Statement stm = con.createStatement();

            try{
                String report = ("C:\\Users\\user\\Documents\\" + "NetBeansProjects\\AplikasiKepegawaian\\src\\" +"aplikasikepegawaian\\reportTransaksi.jrxml");
                    HashMap hash = new HashMap();
                    hash.put("nama", txtcari.getText());
                    JasperReport jrpt = JasperCompileManager.compileReport(report);
                    JasperPrint jprint = JasperFillManager.fillReport(jrpt,hash ,con);
                    JasperViewer.viewReport(jprint, false);

                }catch(Exception e){
                    System.out.println("Laporan tidak Bisa dilihat karena :");
                }

            }catch(Exception e){
                System.out.println(e);
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtnama.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Nama Belum diisi");
            txtnama.requestFocus();
        }else if (cmbjabatan.getSelectedItem().toString().equals("")){
            JOptionPane.showMessageDialog(null, "Jabatan Belum diisi");
            cmbjabatan.requestFocus();
         }else if (txtid.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "No Telpon Belum diisi");
            txtid.requestFocus();
        }else if (txtgaji.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Jabatan Belum Dipilih");
            txtgaji.requestFocus();
        }else if (cmblembur.getSelectedItem().toString().equals("")){
            JOptionPane.showMessageDialog(null, "Lama Jam Lembur Belum diisi");
            cmblembur.requestFocus();
        }else if (txtuanglembur.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Alamat Belum diisi");
            txtuanglembur.requestFocus();
        }else if (txttotal.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Email Belum diisi");
            txttotal.requestFocus();
        }else{
            String[] Field = {"nama", "jabatan","id","gajih","lembur","uanglembur","total"};
            String[] isi = {txtnama.getText(),cmbjabatan.getSelectedItem().toString(),txtid.getText(),txtgaji.getText(),cmblembur.getSelectedItem().toString(),txtuanglembur.getText(),txttotal.getText()};

            new backend_UASPBO().SimpanDBAuto("transaksi", Field, isi);
            new backend_UASPBO().JudulJtable(jTable1, Data);
            new backend_UASPBO().tampilTabel(Data, SQL, jTable1);
            new backend_UASPBO().LebarJTable(jTable1, Lebar);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String[] Field = {"nama", "jabatan","id","gajih","lembur","uanglembur","total"};
        String[] isi = {txtnama.getText(),cmbjabatan.getSelectedItem().toString(),txtid.getText(),txtgaji.getText(),cmblembur.getSelectedItem().toString(),txtuanglembur.getText(),txttotal.getText()};

        new backend_UASPBO().UbahDBAuto("transaksi", "nama", txtnama.getText(), Field, isi);
        JOptionPane.showMessageDialog(null,"Data Pegawai Berhasil diubah");

        new backend_UASPBO().JudulJtable(jTable1, Data);
        new backend_UASPBO().tampilTabel(Data, SQL, jTable1);
        new backend_UASPBO().LebarJTable(jTable1, Lebar);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new backend_UASPBO().HapusDBAuto("transaksi","nama", txtnama.getText());
        JOptionPane.showMessageDialog(null,"Data Berhasil dihapus");

        new backend_UASPBO().JudulJtable(jTable1, Data);
        new backend_UASPBO().tampilTabel(Data, SQL, jTable1);
        new backend_UASPBO().LebarJTable(jTable1, Lebar);

        txtnama.setText("");
        cmbjabatan.setSelectedItem("Pilih Jabatan");
        txtid.setText("");
        txtgaji.setText("");
        cmblembur.setSelectedItem("Pilih lama jam lembur");
        txtuanglembur.setText("");
        txttotal.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();

        txtnama.setText(jTable1.getModel().getValueAt(row,0).toString());
        cmbjabatan.setSelectedItem(jTable1.getModel().getValueAt(row,1).toString());
        txtid.setText(jTable1.getModel().getValueAt(row,2).toString());
        txtgaji.setText(jTable1.getModel().getValueAt(row,3).toString());
        cmblembur.setSelectedItem(jTable1.getModel().getValueAt(row,4).toString());
        txtuanglembur.setText(jTable1.getModel().getValueAt(row,5).toString());
        txttotal.setText(jTable1.getModel().getValueAt(row,5).toString());
// TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
        String Cari ="SELECT*FROM transaksi WHERE nama LIKE '%"+txtcari.getText()+"%' OR nama LIKE '%"+txtcari.getText()+"%'";

        new backend_UASPBO().JudulJtable(jTable1, Data);
        new backend_UASPBO().tampilTabel(Data, Cari, jTable1);
        new backend_UASPBO().LebarJTable(jTable1, Lebar);
    }//GEN-LAST:event_txtcariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiGajih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiGajih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiGajih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiGajih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiGajih().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhitung;
    private javax.swing.JComboBox<String> cmbjabatan;
    private javax.swing.JComboBox<String> cmblembur;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtgaji;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txtuanglembur;
    // End of variables declaration//GEN-END:variables

}
